#!/bin/sh
#
# Set-up a centos chroot
#
scriptdir=$(dirname $(readlink -f $0))
url=https://github.com/TortugaLabs/proot4ci/releases/download/binaries/centos-7.2.1511-rootfs.tar.xz
fatal() {
  echo "$@" 1>&2
  exit 1
}

root="$1" ; [ -z "$root" ] && fatal "No rootdir specified"
[ ! -d "$root" ] && fatal "$root: does not exist"

wget -O- -nv $url | tar -C "$root" -Jxf -
#
# Install some basic yum stuff
#
proot -S "$root" yum update -y
proot -S "$root" yum install -y epel-release
proot -S "$root" yum groupinstall -y buildsys-build

# bin/proot -S <root> [cmd]
