#!/bin/sh
#
# Create a Centos Root
#
[ $# -eq 0 ] && set - centos-7.2.1511-x86_64.rootfs.tar.xz 7 x86_64
if [ $# -ne 3 ] ; then
  cat 2>&1 <<-EOF
	Usage: $0 <tarball> [release] [arch]"

	- release defaults to 7
	- arch defaults to x86_64
	EOF
  exit 1
fi
tarball="$1"
crel="$2"
arch="$3"
repos="
  --repo=http://ow1.localnet/v1/centos-$crel/$crel-os-$arch/ \
  --repo=http://ow1.localnet/cgi-bin/rpmgot.cgi/centos/$crel/updates/$arch/ \
  --repo=http://ow1.localnet/cgi-bin/rpmgot.cgi/centos/$crel/extras/$arch/ \
  --repo=http://ow1.localnet/cgi-bin/rpmgot.cgi/epel/$crel/$arch
"

if [ $EUID -ne 0 ] ; then
   echo "Obtaining root permissions"
   sudo true || exit 1
fi

scriptdir=$(dirname $(readlink -f $0))

root() {
  if [ $EUID -eq 0 ] ; then
    "$@"
  else
    sudo "$@"
  fi
}

root="$(mktemp -d -p "$(dirname $(readlink -f "$tarball"))")"
if [ $EUID -ne 0 ] ; then
  (
    while :
    do
      sleep 1
      sudo -n true
    done
  ) &
  pid=$!
  trap "kill $pid ; sudo -n rm -rf $root" EXIT
else
  trap "rm -rf $root" EXIT
fi

set -e
root $scriptdir/yumroot mkroot -F "$root"
root $scriptdir/yumroot run --selinux $repos "$root" install -y bash yum wget epel-release
root $scriptdir/yumroot run --selinux $repos "$root" groupinstall -y buildsys-build
(
  echo "Tidying up..."
  cd "$root" || exit 1
  rm -rf dev/* var/lib/yum/repos var/lib/yum/history var/log/*
)
echo "Packing $tarball"
root tar -C "$root" -Jcf "$tarball" .
root chown $(id -u):$(id -g) "$tarball"
