#!/bin/sh
#
# chroot set-up
#
scriptdir=$(dirname $(readlink -f $0))
fatal() {
  echo "$@" 1>&2
  exit 1
}
usage() {
  cat 2>&1 <<-EOF
	Usage: $0 <template> <root> [opt args]
	EOF
  exit 1
}

template="$1" ; [ -z "$template" ] && usage
root="$2" ; [ -z "$root" ] && usage ; root=$(readlink -f "$root")
shift 2
[ ! -f "$scriptdir/$template.cfg" ] && fatal "$template: Invalid template"
github="https://github.com/TortugaLabs/proot4ci/releases/download/binaries/"

. "$scriptdir/$template.cfg"

#
# Build proot
#
(
  [ -x $scriptdir/bin/proot ] && exit
  set -e
  mkdir -p $scriptdir/bin
  cd $scriptdir/proot/src || exit 1
  make
  ln -f proot ../../bin
) || exit 1

proot=$scriptdir/bin/proot
if [ ! -d "$root" ] ; then
 mkdir -p "$root" || exit 1
fi

wget -nv -O- $github/$rootfs | tar -C "$root" -Jxf -
op_postcmd
